spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myproject
    username: root
    password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value:
system:
  open-proxy: true
  proxyHost: 127.0.0.1
  proxyPort: 7890
  baseDownloadDir: E:\\图片
  pixiv:
    request-header:
      User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11
      Referer: https://www.pixiv.net/
      cookie: first_visit_datetime_pc=2022-07-10+17%3A10%3A05; p_ab_id=6; p_ab_id_2=5; p_ab_d_id=691196442; yuid_b=U0kEWQA; c_type=42; privacy_policy_notification=0; a_type=0; b_type=1; adr_id=zpzn2XhPxtz3Mx1Lh0ZWgJQ7hIbLjZZMc5MpfXJXQRISutsi; _td=79ef159f-2056-4e84-929a-085a14893022; pt_47mvrj9g=uid=UxGCmQql/amsUNcA7zIH-Q&nid=0&vid=3XEo8q-aMkPA3NizfWoqEQ&vn=2&pvn=1&sact=1662007646717&to_flag=0&pl=IZoRf4OCSv6aouL5bhDEAg*pt*1662007646717; login_ever=yes; privacy_policy_agreement=5; tag_view_ranking=_EOd7bsGyl~0xsDLqCEW6~Lt-oEicbBr~ziiAzr_h04~Ie2c51_4Sp~KN7uxuR89w~RTJMXD26Ak~HY55MqmzzQ~jk9IzfjZ6n~eVxus64GZU~5oPIfUbtd6~RcahSSzeRf~tgP8r-gOe_~_hSAdpN9rx~y3NlVImyly~99-dVV-h9A~LJo91uBPz4~faHcYIP1U0~azESOjmQSV~9Gbahmahac~TqiZfKmSCg~zIv0cf5VVk~zyKU3Q5L4C~U-RInt8VSZ~BSlt10mdnm~-98s6o2-Rp~QaiOjmwQnI~bfM8xJ-4gy~GNcgbuT3T-~-StjcwdYwv~EZQqoW9r8g~KOnmT1ndWG~Xyw8zvsyR4~gpglyfLkWs~wT3Oq8sUOs~qVjnJnSnAY~PwDMGzD6xn~Bd2L9ZBE8q~hW_oUTwHGx~wmxKAirQ_H~aPdvNeJ_XM~4QveACRzn3~FfFuZRxXNV~BU9SQkS-zU~X_1kwTzaXt~pzZvureUki~QwUeUr8yRJ~Sbp1gmMeRy~_-agXPKuAQ~TWrozby2UO~3gc3uGrU1V~qtVr8SCFs5~Ltq1hgLZe3~rqnJSF7cpq~vzTU7cI86f~tws8Fo03IJ~v3nOtgG77A~WVrsHleeCL~_pwIgrV8TB~OUF2gvwPef~eInvgwdvwj~OfvEJkxqVs~0cVg6zK-_N~bjLQIDUtWe~ETjPkL0e6r~MSNRmMUDgC~y8GNntYHsi~MnGbHeuS94~q3eUobDMJW~rI4MmDPPTp~P2D77UwOJp~W9gCxHSDKc~jH0uD88V6F~LprETpwe6C~PGdsi0x43k~FRANJWabF9~Ju2pDAayUA~rrEc0NMJCe~vicUlGNLTn~DpYZ-BAzxm~c7QmKEJ54V~EUwzYuPRbU~faAsMmDFyz~-7RnTas_L3~yREQ8PVGHN~LDlKSdv66y~4gzX-RNalt~m3EJRa33xU~AKT2U2P4W6~xufWQ15ZA3~IMrblZtICw~qkC-JF_MXY~RokSaRBUGr~8OrzSydGQW~X_XTlwG-Er~8Le-BdaoRB~7dpqkQl8TH~oDcj90OVdf~e5VdDyLvtq~hIbSsZ4_QS; PHPSESSID=20225328_tPf2SHNANd5xhUTp3sxm0YPkKOH8HW9e; device_token=1aa2bbc83e3b4c33c1d042b2ca7cfeab; __cf_bm=L7W8BFo021J4MoaUub2S3lHDwSl.jeuxmyKKtnOayCU-1682409599-0-AXZaD/pegUqrcTpAP8LD/oK/j0OUGtad3OMI6zlUcDI8PviuDOloX8cEnvRZndj4/cUPfywy6sfWF6n2ZZa9Uova4/1eEg8lQHF4UnCA+gCVq7qRlZAslDYUL6gkRPri4F0cEjpAYSCdIEo5pEGSPWTr0np74z/wajM8ZT5DR8fU; QSI_S_ZN_5hF4My7Ad6VNNAi=v:0:0
    charset-name: utf-8
    username: 54210650
    password: qaz360782
  thread:
    core-size: 8
    max-size: 50
    keep-alive-time: 60
  selenium:
    driver-name: webdriver.edge.driver
    driver-dir: D:\Tools\edgeDriver\msedgedriver.exe
logging:
  level:
    com.sakanal.web: info
