
logging:
  level:
    com.sakanal.leipin: debug
config:
  download-dir: D:\
  job-responsibilities-description:
    - 职位描述
    - 工作职责
    - 岗位职责
    - 职责描述
  job-qualification-description:
    - 任职资格
    - 任职要求
    - 职位要求
    - 岗位要求
  simple-search-params:
    #城市
    city: 410
    #城市+地区
    dq: 410
    #发布时间 1 3 7 30
    pubTime:
    #页码-1
    currentPage: 0
    #页面尺寸
    pageSize: 40
    #经验 0 1 2 1&3
    workYearCode: 0
    #来源
    sfrom: search_job_pc
    suggestTag:
    suggestId:
    compId:
    compName:
    #名企
    compTag:
    #行业
    industry:
    #薪资 3&5
    salary:
    #职位类型
    jobKind:
    #企业规模
    compScale:
    #企业性质
    compKind:
    #融资阶段
    compStage:
    #学历
    eduLevel:
    otherCity:
    ckId:
    skId:
    fkId:
    #input点击搜索，condition点击条件，page点击页面
    scene: input
  sign-title:
    - 安全中心-验证码
  driver-name: webdriver.edge.driver
  driver-dir: D:\Tools\edgeDriver\msedgedriver.exe
server:
  port: 8888
